### ISSUE TITLE
More than 3 items in map cause crash

### ISSUE THREAD

**Issue by snowe2010** [grosser/parallel#125]
I'm not sure what is going on here, but if I run this code

```
require 'watir-webdriver'
require 'parallel'

results = Parallel.map(%w|d d f f|, :in_processes=>4) do |one_letter|
        b = Watir::Browser.new :phantomjs
        b.goto 'dapadenial001.recondo.vci:8080'
        puts b.url
        b.close
end
```

I receive this stack trace

```
[~]$ ruby test.rb
about:blank
about:blank
/usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:66:in `create_response': unexpected response, code=404, content-type="text/plain" (Selenium::WebDriver::Error::WebDriverError)
Error 404: Not Found
File not found
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:200:in `switchToDefaultContent'
        from /usr/local/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/target_locator.rb:77:in `default_content'
        from /usr/local/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.7.0/lib/watir-webdriver/browser.rb:386:in `assert_exists'
        from /usr/local/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.7.0/lib/watir-webdriver/browser.rb:111:in `url'
        from test.rb:8:in `block in <main>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:436:in `call'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:436:in `call_with_index'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:342:in `process_incoming_jobs'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:324:in `block in worker'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:317:in `fork'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:317:in `worker'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:305:in `block in create_workers'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:304:in `each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:304:in `create_workers'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:263:in `work_in_processes'
        from /usr/local/lib/ruby/gems/1.9.1/gems/parallel-1.4.1/lib/parallel.rb:193:in `map'
        from test.rb:4:in `<main>'
[~]$
```

Note that this only happens when there are more than 3 items in the map. It never happens with 3 or less.

**Comment by grosser** [comment]
Possibly they all connect to the same phantomjs or something like that oO
I don't think this is a problem in parallel / if you do something without phantomjs it will work.
