### ISSUE TITLE
Ignores SIGINT when using JRuby

### ISSUE THREAD

**Issue by msavy** [grosser/parallel#133]
MRI works as expected

```ShellSession
[msavy@MacBook-Pro .rbenv]$ rbenv shell 2.2.2
[msavy@MacBook-Pro .rbenv]$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
[msavy@MacBook-Pro .rbenv]$ gem install parallel
Fetching: parallel-1.4.1.gem (100%)
Successfully installed parallel-1.4.1
Parsing documentation for parallel-1.4.1
Installing ri documentation for parallel-1.4.1
Done installing documentation for parallel after 0 seconds
1 gem installed
[msavy@MacBook-Pro .rbenv]$ ruby -e 'require "parallel"; Parallel.each([1,2,3], :in_threads => 3) {|n| puts "Started" ;sleep 30; puts n }'
Started
Started
Started
^CParallel execution interrupted, exiting ...
/Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:406:in `block in trap_interrupt': Interrupt (Interrupt)
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:353:in `call'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:353:in `join'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:353:in `block in wait_for_threads'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:351:in `map'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:351:in `wait_for_threads'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:142:in `block in in_threads'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:394:in `kill_on_ctrl_c'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:142:in `in_threads'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:241:in `work_in_threads'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:191:in `map'
	from /Users/msavy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/parallel-1.4.1/lib/parallel.rb:154:in `each'
	from -e:1:in `<main>'
```

under JRuby it seems to lose/ignore the signal
```ShellSession
[msavy@MacBook-Pro .rbenv]$ rbenv shell jruby-1.7.20
[msavy@MacBook-Pro .rbenv]$ gem install parallel
Fetching: parallel-1.4.1.gem (100%)
Successfully installed parallel-1.4.1
1 gem installed
[msavy@MacBook-Pro .rbenv]$ ruby -e 'require "parallel"; Parallel.each([1,2,3], :in_threads => 3) {|n| puts "Started" ;sleep 30; puts n }'
StartedStarted
Started

^C^C^C^C^C^C^C^C23
1
```

**Comment by grosser** [comment]
jruby needs "SIGINT" to kind of do what mri does (still a little different but shold be close enough)

playing with this:

```
ruby -Ilib -rparallel -e 'Parallel.map([1,2,3]){ exec %{trap "sleep 100" 2; sleep 100} }'
```

 - mri stops executing but does not kill -9 it's children ... bad ...
 - jruby hangs forever and cannot be Ctrl+C-ed which looks like what you are seeing

... so yeah needs more logic and bette tests :)

do you want to work on this ? / I might find time in a couple of days but would be great to have a fresh set of eyes on that crazy code ...

**Comment by grosser** [comment]
1.5 should fix that ... just disabling all this signal foobar for jruby since we are dealing with threads anyway ...

**Comment by msavy** [comment]
Sorry for not getting around to this, I've been mega busy on a bunch of other tasks.

I can't think off the top of my head why it would be bad to get rid of the signal stuff for threads, so perhaps that's a good solution. Is there any reason that principle can't be extended to threads in general, rather than just JRuby impl?

**Comment by grosser** [comment]
blergh ... because it was rescuing interrupt ... removing this means we no longer have to kill the threads ... only sad part is I know I added it for a reason because some threads would raise interrupt and I did not know why it happened ... maybe we can find out if it happens again ... 

1.6.0
