### ISSUE TITLE
Parallel::DeadWorker: Parallel::DeadWorker when processing multiple files

### ISSUE THREAD

**Issue by antarr** [grosser/parallel#286]
I'm trying to update a script that imports data from a CSV file. I'm getting `Parallel::DeadWorker: Parallel::DeadWorker` when it gets to the end of one of the files.

***full error***
```
bundle exec rake voter_records:default:seed STATE='OH'
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /Users/antarr/Code/wevote/config/application.rb:20)
/Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/compile_cache/iseq.rb:19: warning: regular expression has ']' without escape: /^0]/
/Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/compile_cache/iseq.rb:19: warning: regular expression has ']' without escape: /^0]/
W, [2020-11-08T22:38:21.535629 #94649]  WARN -- Skylight: [SKYLIGHT] [4.3.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xab.csv to VoterRecord...

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xag.csv to VoterRecord...

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xac.csv to VoterRecord...

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xad.csv to VoterRecord...

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xaa.csv to VoterRecord...

Importing records from /Users/antarr/Code/wevote/data_files/voter_records/OH/xae.csv to VoterRecord...
Time: 00:07:32                                                                                                                                                    ᗧ 100% Progress
WARNING: Your progress bar is currently at 197009 out of 197009 and cannot be incremented. In v2.0.0 this will become a ProgressBar::InvalidProgressError.
Time: 00:07:32                                                                                                                                                    ᗧ 100% Progress
Traceback (most recent call last):
        45: from /Users/antarr/.rbenv/versions/2.6.2/bin/bundle:23:in `<main>'
        44: from /Users/antarr/.rbenv/versions/2.6.2/bin/bundle:23:in `load'
        43: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
        42: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
        41: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
        40: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
        39: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        38: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
        37: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        36: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        35: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        34: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
        33: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
        32: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
        31: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
        30: from /Users/antarr/.rbenv/versions/2.6.2/bin/rake:23:in `<top (required)>'
        29: from /Users/antarr/.rbenv/versions/2.6.2/bin/rake:23:in `load'
        28: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
        27: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
        26: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
        25: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
        24: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
        23: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
        22: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
        21: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
        20: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
        19: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
        18: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
        17: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
        16: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
        15: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
        14: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
        13: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
        12: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
        11: from /Users/antarr/Code/wevote/lib/tasks/voter_records/default.rake:13:in `block (3 levels) in <main>'
        10: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:278:in `map'
         9: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:374:in `work_in_processes'
         8: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `create_workers'
         7: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each_with_index'
         6: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:435:in `each'
         5: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:436:in `block in create_workers'
         4: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `worker'
         3: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:445:in `fork'
         2: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:454:in `block in worker'
         1: from /Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:480:in `process_incoming_jobs'
/Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:480:in `dump': can't dump IO (TypeError)
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker


Caused by:
EOFError: end of file reached

Tasks: TOP => voter_records:default:seed
(See full trace by running task with --trace)
```

***rake task***
```
namespace :voter_records do
  namespace :default do
    task :seed, [:abbr] => :environment do |_t, _args|
      state = ENV['STATE']
      @model = LegiscanModel::State.find_by(abbr: state)

      load 'lib/utils/csv_importer.rb'
      include Utils::CsvImporter

      dir_path = "#{Rails.root}/data_files/voter_records/#{state}"
      batch_id = 0
      file_names = Dir.entries(dir_path)
      Parallel.map(file_names, in_processes: (`sysctl -n hw.ncpu`.to_i/2)) do |file_name|
        next if (file_name == '.') || (file_name == '..')

        batch_id += 1
        import_csv("#{dir_path}/#{file_name}", VoterRecord, 1000, batch_id)
      end
    end

    def transformations
      {
        'CA' => {
          'address' => {
            'address_line_1' => 'RESIDENTIAL_ADDRESS1',
            'address_line_2' => 'RESIDENTIAL_SECONDARY_ADDR',
            'city' => 'RESIDENTIAL_CITY',
            'zip' => 'RESIDENTIAL_ZIP',
            'zip_plus_4' => 'RESIDENTIAL_ZIP_PLUS4'
          },
          'voter_record' => {
            'first_name' => 'FIRST_NAME',
            'last_name' => 'LAST_NAME',
            'middle_name' => 'MIDDLE_NAME',
            'dob' => 'DOB',
            'status' => 'VOTER_STATUS',
            'state_representative_district_id' => 'STATE_REPRESENTATIVE_DISTRICT',
            'state_senate_district_id' => 'STATE_SENATE_DISTRICT',
            'congressional_senate_district_id' => 'CONGRESSIONAL_DISTRICT'
          }
        },
        'OH' => {
          'address' => {
            'address_line_1' => 'RESIDENTIAL_ADDRESS1',
            'address_line_2' => 'RESIDENTIAL_SECONDARY_ADDR',
            'city' => 'RESIDENTIAL_CITY',
            'zip' => 'RESIDENTIAL_ZIP',
            'zip_plus_4' => 'RESIDENTIAL_ZIP_PLUS4'
          },
          'voter_record' => {
            'first_name' => 'FIRST_NAME',
            'last_name' => 'LAST_NAME',
            'middle_name' => 'MIDDLE_NAME',
            'dob' => 'DOB',
            'status' => 'VOTER_STATUS',
            'state_representative_district_id' => 'STATE_REPRESENTATIVE_DISTRICT',
            'state_senate_district_id' => 'STATE_SENATE_DISTRICT',
            'congressional_senate_district_id' => 'CONGRESSIONAL_DISTRICT'
          }
        }
      }
    end

    def map_voter_record(header, line, batch_id)
      {
        state_id: @model.id,
        first_name: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])],
        last_name: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])],
        middle_name: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])],
        dob: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])],
        status: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])],
        state_representative_district_id: get_district_id('HD', line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])]),
        state_senate_district_id: get_district_id('SD', line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])]),
        congressional_district_id: "HD-OH-#{line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['first_name'])].sub!(/^0]/, '')}",
        congressional_senate_district_id: 'SD-OH',
        batch_id: batch_id
      }
    end

    def map_address(header, line, batch_id)
      {
        state_id: @model.id,
        address_line_1: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['address_line_1'])],
        address_line_2: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['address_line_2'])],
        city: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['city'])],
        zip: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['zip'])],
        zip_plus_4: line[header.index(FIELD_MAPPINGS[state.to_s]['voter_record']['zip_plus_4'])],
        batch_id: batch_id
      }
    end

    def get_district_id(district_prefix, district_id)
      case district_id.to_i.digits.count
      when 1
        "#{district_prefix}-00#{district_id.to_i}"
      when 2
        "#{district_prefix}-0#{district_id.to_i}"
      else
        "#{district_prefix}-#{district_id.to_i}"
      end
    end

    def import_csv(csv, model, max_records = 1000, batch_id)
      puts "\nImporting records from #{csv} to #{model}...\n"

      total = `wc -l < "#{csv}"`.to_i

      File.open(csv, 'r') do |file|
        header = CSV.parse(file.readline).flatten
        voter_records = []
        addresses = []
        sha2_address_ids = {}
        pbar = Utils.get_progress_bar(total, title: csv)

        file.each_line do |line|
          row = nil
          begin
            row = CSV.parse(line).flatten
          rescue StandardError
            row = CSV.parse(line.scrub('')).flatten
          end

          vr = VoterRecord.new(map_voter_record(header, row, batch_id))
          addr = Address.new(map_address(header, row, batch_id))
          vr.sha2_address_id = addr.as_sha2
          addr.sha2_address_id = addr.as_sha2
          addresses << addr unless sha2_address_ids[addr.as_sha2]
          sha2_address_ids[addr.as_sha2] = true
          voter_records << vr

          if voter_records.length >= max_records
            VoterRecord.import voter_records
            voter_records = []
          end

          if addresses.length >= max_records
            Address.import addresses, on_duplicate_key_update: { constraint_name: :for_upsert }
            addresses = []
          end

          pbar.increment
        end

        Address.import addresses, on_duplicate_key_update: { constraint_name: :for_upsert }
        VoterRecord.import voter_records
        pbar.increment
      end
    end
  end
end
```

**Comment by grosser** [comment]
/Users/antarr/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/parallel-1.19.2/lib/parallel.rb:480:in
`dump': can't dump IO (TypeError)

sounds like it's trying to send back an IO object, or an exception was
raised that includes and IO

I'd recommend doing:

begin

  x = import_csv(...)

  Marshal.dump(x)

  x

rescue Exception

  puts "EXCEPTION #{$!}"

  raise

end

to find out if it either returned an IO object or it raised something
that included an IO

**Comment by antarr** [comment]
I was able to get it working by using threads instead of processes
